/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Locations */
        get: operations["locations_api_v1_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Staff */
        get: operations["list_staff_api_v1_staff_get"];
        put?: never;
        /** Invite Staff */
        post: operations["invite_staff_api_v1_staff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Staff */
        get: operations["get_staff_api_v1_staff__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Staff */
        patch: operations["update_staff_api_v1_staff__user_id__patch"];
        trace?: never;
    };
    "/api/v1/staff/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Staff Roles */
        put: operations["set_staff_roles_api_v1_staff__user_id__roles_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Staff */
        post: operations["deactivate_staff_api_v1_staff__user_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/{user_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate Staff */
        post: operations["reactivate_staff_api_v1_staff__user_id__reactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Permissions */
        get: operations["list_permissions_api_v1_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_api_v1_roles_get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_api_v1_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Role */
        delete: operations["delete_role_api_v1_roles__role_id__delete"];
        options?: never;
        head?: never;
        /** Update Role */
        patch: operations["update_role_api_v1_roles__role_id__patch"];
        trace?: never;
    };
    "/api/v1/roles/{role_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Role Permissions */
        put: operations["set_role_permissions_api_v1_roles__role_id__permissions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_v1_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch Ledger */
        get: operations["batch_ledger_api_v1_batches__batch_id__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive */
        post: operations["receive_api_v1_stock_receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust */
        post: operations["adjust_api_v1_stock_adjustments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer */
        post: operations["transfer_api_v1_stock_transfers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/fefo/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fefo Preview */
        post: operations["fefo_preview_api_v1_stock_fefo_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/expiry-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expiry Risk */
        get: operations["expiry_risk_api_v1_stock_expiry_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movements */
        get: operations["movements_api_v1_stock_movements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Patients */
        get: operations["search_patients_api_v1_patients_get"];
        put?: never;
        /** Create Patient */
        post: operations["create_patient_api_v1_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacy/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_v1_pharmacy_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_v1_pharmacy_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacy/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_v1_pharmacy_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacy/orders/{order_id}/pick-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pick List */
        get: operations["pick_list_api_v1_pharmacy_orders__order_id__pick_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacy/orders/{order_id}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch */
        post: operations["dispatch_api_v1_pharmacy_orders__order_id__dispatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacy/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_pharmacy_orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacy/orders/{order_id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return Items */
        post: operations["return_items_api_v1_pharmacy_orders__order_id__return_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pharmacy/requesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Requesters
         * @description Active staff who can raise requisitions (for the pharmacist's 'on behalf of' picker).
         */
        get: operations["requesters_api_v1_pharmacy_requesters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Audit */
        get: operations["verify_audit_api_v1_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description Role-aware KPIs: tiles the caller can't see are returned as null.
         */
        get: operations["dashboard_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dev Users
         * @description Seeded accounts for the local sign-in picker (AUTH_MODE=dev only).
         */
        get: operations["dev_users_api_v1_dev_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Token
         * @description Mint a local token that mimics an Entra access token (AUTH_MODE=dev only).
         */
        post: operations["dev_token_api_v1_dev_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustmentIn */
        AdjustmentIn: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Qty Delta */
            qty_delta: number;
            /**
             * Reason
             * @enum {string}
             */
            reason: "count_correction" | "damaged" | "expired" | "other";
            /** Note */
            note: string;
        };
        /** AllocationOut */
        AllocationOut: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Batch No */
            batch_no: string;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Qty */
            qty: number;
            /** Qty Returned */
            qty_returned: number;
        };
        /** AuditOut */
        AuditOut: {
            /** Id */
            id: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Email */
            actor_email: string | null;
            /** Actor Type */
            actor_type: string;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string | null;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /** Ip */
            ip: string | null;
        };
        /** AuditVerifyOut */
        AuditVerifyOut: {
            /** Ok */
            ok: boolean;
            /** First Bad Id */
            first_bad_id: number | null;
        };
        /**
         * BatchRow
         * @description One batch at one location (a stock_balances row), as shown in 'All Active Batches'.
         */
        BatchRow: {
            /**
             * Balance Id
             * Format: uuid
             */
            balance_id: string;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Item Name */
            item_name: string;
            /** Sku */
            sku: string;
            item_type: components["schemas"]["ItemType"];
            schedule: components["schemas"]["DrugSchedule"];
            /** Batch No */
            batch_no: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Days To Expiry */
            days_to_expiry: number;
            /**
             * Expiry Status
             * @enum {string}
             */
            expiry_status: "expired" | "critical" | "warning" | "ok";
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Location Name */
            location_name: string;
            /** Bin Code */
            bin_code: string | null;
            /** Qty On Hand */
            qty_on_hand: number;
            /** Qty Reserved */
            qty_reserved: number;
            /** Qty Available */
            qty_available: number;
            /** Unit Cost */
            unit_cost: string;
            /** Mrp */
            mrp: string;
            /** Valuation */
            valuation: string;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Stock Value */
            stock_value: string | null;
            /** Active Batches */
            active_batches: number | null;
            /** Expiring 30 */
            expiring_30: number | null;
            /** Expired On Hand */
            expired_on_hand: number | null;
            /** Below Par Items */
            below_par_items: number | null;
            /** Orders Awaiting Dispatch */
            orders_awaiting_dispatch: number | null;
            /** Counter Sales Today */
            counter_sales_today: string | null;
            /** Requisitions Today */
            requisitions_today: number | null;
        };
        /** DevTokenIn */
        DevTokenIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** DevTokenOut */
        DevTokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** DevUser */
        DevUser: {
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Job Title */
            job_title: string | null;
            /** Roles */
            roles: string[];
        };
        /**
         * DrugSchedule
         * @enum {string}
         */
        DrugSchedule: "none" | "H" | "H1" | "X";
        /** ExpiryBucket */
        ExpiryBucket: {
            /** Bucket */
            bucket: string;
            /** Batches */
            batches: number;
            /** Units */
            units: number;
            /** Value */
            value: string;
        };
        /** FefoPick */
        FefoPick: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Batch No */
            batch_no: string;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Qty */
            qty: number;
            /** Bin Code */
            bin_code?: string | null;
        };
        /** FefoPreviewIn */
        FefoPreviewIn: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Qty */
            qty: number;
        };
        /** FefoPreviewOut */
        FefoPreviewOut: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Requested */
            requested: number;
            /** Allocatable */
            allocatable: number;
            /** Shortfall */
            shortfall: number;
            /** Picks */
            picks: components["schemas"]["FefoPick"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemCreate */
        ItemCreate: {
            /** Name */
            name: string;
            /** Generic Name */
            generic_name?: string | null;
            type: components["schemas"]["ItemType"];
            /** @default none */
            schedule: components["schemas"]["DrugSchedule"];
            /** Dosage Form */
            dosage_form?: string | null;
            /** Strength */
            strength?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Hsn Code */
            hsn_code?: string | null;
            /**
             * Gst Rate
             * @default 12
             */
            gst_rate: number | string;
            /**
             * Uom
             * @default unit
             */
            uom: string;
            /** Mrp */
            mrp: number | string;
            /**
             * Par Min
             * @default 0
             */
            par_min: number;
            /**
             * Par Max
             * @default 0
             */
            par_max: number;
            /**
             * Is Cold Chain
             * @default false
             */
            is_cold_chain: boolean;
            /** Sku */
            sku: string;
        };
        /** ItemOut */
        ItemOut: {
            /** Name */
            name: string;
            /** Generic Name */
            generic_name?: string | null;
            type: components["schemas"]["ItemType"];
            /** @default none */
            schedule: components["schemas"]["DrugSchedule"];
            /** Dosage Form */
            dosage_form?: string | null;
            /** Strength */
            strength?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Hsn Code */
            hsn_code?: string | null;
            /**
             * Gst Rate
             * @default 12
             */
            gst_rate: string;
            /**
             * Uom
             * @default unit
             */
            uom: string;
            /** Mrp */
            mrp: string;
            /**
             * Par Min
             * @default 0
             */
            par_min: number;
            /**
             * Par Max
             * @default 0
             */
            par_max: number;
            /**
             * Is Cold Chain
             * @default false
             */
            is_cold_chain: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sku */
            sku: string;
            /** Is Active */
            is_active: boolean;
            /**
             * On Hand
             * @default 0
             */
            on_hand: number;
            /**
             * Available
             * @default 0
             */
            available: number;
            /**
             * Below Par
             * @default false
             */
            below_par: boolean;
        };
        /**
         * ItemType
         * @enum {string}
         */
        ItemType: "drug" | "consumable" | "iol" | "equipment";
        /** ItemUpdate */
        ItemUpdate: {
            /** Name */
            name?: string | null;
            /** Generic Name */
            generic_name?: string | null;
            schedule?: components["schemas"]["DrugSchedule"] | null;
            /** Dosage Form */
            dosage_form?: string | null;
            /** Strength */
            strength?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Hsn Code */
            hsn_code?: string | null;
            /** Gst Rate */
            gst_rate?: number | string | null;
            /** Mrp */
            mrp?: number | string | null;
            /** Par Min */
            par_min?: number | null;
            /** Par Max */
            par_max?: number | null;
            /** Is Cold Chain */
            is_cold_chain?: boolean | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** LedgerOut */
        LedgerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Qty Delta */
            qty_delta: number;
            reason: components["schemas"]["LedgerReason"];
            /** Note */
            note: string | null;
            /** Ref Type */
            ref_type: string | null;
            /** Ref Id */
            ref_id: string | null;
            /** Actor Id */
            actor_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Item Name
             * @default
             */
            item_name: string;
            /**
             * Sku
             * @default
             */
            sku: string;
            /**
             * Batch No
             * @default
             */
            batch_no: string;
            /**
             * Location Name
             * @default
             */
            location_name: string;
            /** Actor Name */
            actor_name?: string | null;
        };
        /**
         * LedgerReason
         * @enum {string}
         */
        LedgerReason: "receipt" | "adjustment" | "transfer_out" | "transfer_in" | "issue" | "return_in" | "writeoff";
        /** LocationOut */
        LocationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            type: components["schemas"]["LocationType"];
        };
        /**
         * LocationType
         * @enum {string}
         */
        LocationType: "warehouse" | "pharmacy" | "ot_store";
        /** MeOut */
        MeOut: {
            user: components["schemas"]["StaffOut"];
            /** Permissions */
            permissions: string[];
            /** Permission Scopes */
            permission_scopes: {
                [key: string]: (string | null)[];
            };
            /** Locations */
            locations: components["schemas"]["LocationOut"][];
        };
        /**
         * OrderChannel
         * @enum {string}
         */
        OrderChannel: "counter_sale" | "requisition";
        /** OrderCreate */
        OrderCreate: {
            channel: components["schemas"]["OrderChannel"];
            /** Lines */
            lines: components["schemas"]["OrderLineIn"][];
            /** Patient Id */
            patient_id?: string | null;
            /** Walk In Name */
            walk_in_name?: string | null;
            /** Walk In Phone */
            walk_in_phone?: string | null;
            /** Prescription Ref */
            prescription_ref?: string | null;
            /** Prescriber Name */
            prescriber_name?: string | null;
            /** Requested By Id */
            requested_by_id?: string | null;
            /** Department */
            department?: string | null;
            /** Surgery Ref */
            surgery_ref?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** OrderLineIn */
        OrderLineIn: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Qty */
            qty: number;
        };
        /** OrderLineOut */
        OrderLineOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Line No */
            line_no: number;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Item Name */
            item_name: string;
            /** Sku */
            sku: string;
            /** Schedule */
            schedule: string;
            /** Qty */
            qty: number;
            /** Unit Price */
            unit_price: string;
            /** Gst Rate */
            gst_rate: string;
            /** Line Total */
            line_total: string;
            /** Qty Returned */
            qty_returned: number;
            /** Allocations */
            allocations: components["schemas"]["AllocationOut"][];
        };
        /** OrderOut */
        OrderOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Order No */
            order_no: string;
            channel: components["schemas"]["OrderChannel"];
            status: components["schemas"]["OrderStatus"];
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Location Name */
            location_name: string;
            /** Party Name */
            party_name: string;
            patient: components["schemas"]["PatientOut"] | null;
            /** Walk In Name */
            walk_in_name: string | null;
            /** Walk In Phone */
            walk_in_phone: string | null;
            /** Prescription Ref */
            prescription_ref: string | null;
            /** Prescriber Name */
            prescriber_name: string | null;
            /** Requested By Id */
            requested_by_id: string | null;
            /** Requested By Name */
            requested_by_name: string | null;
            /** Department */
            department: string | null;
            /** Surgery Ref */
            surgery_ref: string | null;
            /** Notes */
            notes: string | null;
            /** Subtotal */
            subtotal: string;
            /** Gst Amount */
            gst_amount: string;
            /** Total */
            total: string;
            /** Invoice No */
            invoice_no: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Name */
            created_by_name: string;
            /** Dispatched At */
            dispatched_at: string | null;
            /** Lines */
            lines: components["schemas"]["OrderLineOut"][];
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "allocated" | "dispatched" | "partially_returned" | "returned" | "cancelled";
        /** Page[AuditOut] */
        Page_AuditOut_: {
            /** Items */
            items: components["schemas"]["AuditOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[BatchRow] */
        Page_BatchRow_: {
            /** Items */
            items: components["schemas"]["BatchRow"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[ItemOut] */
        Page_ItemOut_: {
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[LedgerOut] */
        Page_LedgerOut_: {
            /** Items */
            items: components["schemas"]["LedgerOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[OrderOut] */
        Page_OrderOut_: {
            /** Items */
            items: components["schemas"]["OrderOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[StaffOut] */
        Page_StaffOut_: {
            /** Items */
            items: components["schemas"]["StaffOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PatientIn */
        PatientIn: {
            /** Mrn */
            mrn: string;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Age */
            age?: number | null;
            /** Gender */
            gender?: string | null;
        };
        /** PatientOut */
        PatientOut: {
            /** Mrn */
            mrn: string;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Age */
            age?: number | null;
            /** Gender */
            gender?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** PermissionOut */
        PermissionOut: {
            /** Code */
            code: string;
            /** Module */
            module: string;
            /** Description */
            description: string;
        };
        /** PickListOut */
        PickListOut: {
            /** Order No */
            order_no: string;
            /** Location Name */
            location_name: string;
            /** Party Name */
            party_name: string;
            /** Rows */
            rows: components["schemas"]["PickListRow"][];
        };
        /** PickListRow */
        PickListRow: {
            /** Line No */
            line_no: number;
            /** Item Name */
            item_name: string;
            /** Sku */
            sku: string;
            /** Batch No */
            batch_no: string;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Bin Code */
            bin_code: string | null;
            /** Qty */
            qty: number;
        };
        /** ReceiptIn */
        ReceiptIn: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Batch No */
            batch_no: string;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Mfg Date */
            mfg_date?: string | null;
            /** Qty */
            qty: number;
            /** Unit Cost */
            unit_cost: number | string;
            /** Mrp */
            mrp?: number | string | null;
            /** Supplier Name */
            supplier_name?: string | null;
            /** Bin Code */
            bin_code?: string | null;
        };
        /** ReturnIn */
        ReturnIn: {
            /** Lines */
            lines: components["schemas"]["ReturnLineIn"][];
            /** Reason */
            reason: string;
        };
        /** ReturnLineIn */
        ReturnLineIn: {
            /**
             * Line Id
             * Format: uuid
             */
            line_id: string;
            /** Qty */
            qty: number;
        };
        /** RoleAssignmentIn */
        RoleAssignmentIn: {
            /**
             * Role Id
             * Format: uuid
             */
            role_id: string;
            /** Location Id */
            location_id?: string | null;
        };
        /** RoleAssignmentOut */
        RoleAssignmentOut: {
            /**
             * Role Id
             * Format: uuid
             */
            role_id: string;
            /** Role Name */
            role_name: string;
            /** Location Id */
            location_id: string | null;
            /** Location Name */
            location_name: string | null;
        };
        /** RoleCreate */
        RoleCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Permissions
             * @default []
             */
            permissions: string[];
        };
        /** RoleOut */
        RoleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Is System */
            is_system: boolean;
            /** Is Immutable */
            is_immutable: boolean;
            /** Permissions */
            permissions: string[];
            /** Permission Count */
            permission_count: number;
            /** User Count */
            user_count: number;
        };
        /** RolePermissionsUpdate */
        RolePermissionsUpdate: {
            /** Permissions */
            permissions: string[];
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** StaffCreate */
        StaffCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Job Title */
            job_title?: string | null;
            /** Department */
            department?: string | null;
            /** Roles */
            roles: components["schemas"]["RoleAssignmentIn"][];
        };
        /** StaffOut */
        StaffOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Job Title */
            job_title: string | null;
            /** Department */
            department: string | null;
            status: components["schemas"]["UserStatus"];
            /** Last Login At */
            last_login_at: string | null;
            /** Linked */
            linked: boolean;
            /** Roles */
            roles: components["schemas"]["RoleAssignmentOut"][];
        };
        /** StaffRolesUpdate */
        StaffRolesUpdate: {
            /** Roles */
            roles: components["schemas"]["RoleAssignmentIn"][];
        };
        /** StaffUpdate */
        StaffUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Job Title */
            job_title?: string | null;
            /** Department */
            department?: string | null;
        };
        /** TransferIn */
        TransferIn: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /**
             * From Location Id
             * Format: uuid
             */
            from_location_id: string;
            /**
             * To Location Id
             * Format: uuid
             */
            to_location_id: string;
            /** Qty */
            qty: number;
            /** Note */
            note?: string | null;
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "invited" | "active" | "inactive";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    locations_api_v1_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"][];
                };
            };
        };
    };
    list_staff_api_v1_staff_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: components["schemas"]["UserStatus"] | null;
                role_id?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StaffOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_staff_api_v1_staff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staff_api_v1_staff__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_staff_api_v1_staff__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_staff_roles_api_v1_staff__user_id__roles_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffRolesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_staff_api_v1_staff__user_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_staff_api_v1_staff__user_id__reactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_permissions_api_v1_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionOut"][];
                };
            };
        };
    };
    list_roles_api_v1_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"][];
                };
            };
        };
    };
    create_role_api_v1_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_api_v1_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_v1_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_role_permissions_api_v1_roles__role_id__permissions_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolePermissionsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_items_get: {
        parameters: {
            query?: {
                q?: string | null;
                type?: components["schemas"]["ItemType"] | null;
                dispensable?: boolean;
                include_inactive?: boolean;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ItemOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_batches_get: {
        parameters: {
            query?: {
                q?: string | null;
                location_id?: string | null;
                item_id?: string | null;
                expiry_status?: ("expired" | "critical" | "warning" | "ok") | null;
                include_empty?: boolean;
                sort?: "received_desc" | "received_asc" | "expiry_asc" | "expiry_desc" | "name_asc" | "qty_desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BatchRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_ledger_api_v1_batches__batch_id__ledger_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_api_v1_stock_receipts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_api_v1_stock_adjustments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_api_v1_stock_transfers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fefo_preview_api_v1_stock_fefo_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FefoPreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FefoPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expiry_risk_api_v1_stock_expiry_risk_get: {
        parameters: {
            query?: {
                location_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpiryBucket"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    movements_api_v1_stock_movements_get: {
        parameters: {
            query?: {
                location_id?: string | null;
                reason?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LedgerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_patients_api_v1_patients_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_api_v1_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_v1_pharmacy_orders_get: {
        parameters: {
            query?: {
                channel?: components["schemas"]["OrderChannel"] | null;
                status?: components["schemas"]["OrderStatus"] | null;
                q?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                sort?: "date_desc" | "date_asc" | "total_desc" | "total_asc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrderOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_v1_pharmacy_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_v1_pharmacy_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pick_list_api_v1_pharmacy_orders__order_id__pick_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispatch_api_v1_pharmacy_orders__order_id__dispatch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_pharmacy_orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    return_items_api_v1_pharmacy_orders__order_id__return_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requesters_api_v1_pharmacy_requesters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                action?: string | null;
                entity_type?: string | null;
                entity_id?: string | null;
                actor?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_api_v1_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyOut"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    dev_users_api_v1_dev_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevUser"][];
                };
            };
        };
    };
    dev_token_api_v1_dev_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevTokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
