"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 11:37:36.647567
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


APPEND_ONLY_TABLES = ("audit_log", "stock_ledger")


def upgrade() -> None:
    op.execute("CREATE SEQUENCE pharmacy_order_no_seq")
    op.execute("CREATE SEQUENCE pharmacy_invoice_no_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_email", sa.String(length=254), nullable=True),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("prev_hash", sa.String(length=64), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_log_ts"), "audit_log", ["ts"], unique=False)
    op.create_table(
        "items",
        sa.Column("sku", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("generic_name", sa.String(length=200), nullable=True),
        sa.Column("type", sa.Enum("drug", "consumable", "iol", "equipment", name="item_type"), nullable=False),
        sa.Column("schedule", sa.Enum("none", "H", "H1", "X", name="drug_schedule"), nullable=False),
        sa.Column("dosage_form", sa.String(length=60), nullable=True),
        sa.Column("strength", sa.String(length=60), nullable=True),
        sa.Column("manufacturer", sa.String(length=120), nullable=True),
        sa.Column("hsn_code", sa.String(length=12), nullable=True),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("uom", sa.String(length=20), nullable=False),
        sa.Column("mrp", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("par_min", sa.Integer(), nullable=False),
        sa.Column("par_max", sa.Integer(), nullable=False),
        sa.Column("is_cold_chain", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("sku", name=op.f("uq_items_sku")),
    )
    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=False)
    op.create_table(
        "locations",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.Enum("warehouse", "pharmacy", "ot_store", name="location_type"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("code", name=op.f("uq_locations_code")),
    )
    op.create_table(
        "patients",
        sa.Column("mrn", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=12), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
        sa.UniqueConstraint("mrn", name=op.f("uq_patients_mrn")),
    )
    op.create_index(op.f("ix_patients_name"), "patients", ["name"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("module", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_permissions")),
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_immutable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "users",
        sa.Column("oid", sa.String(length=64), nullable=True),
        sa.Column("tid", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("department", sa.String(length=120), nullable=True),
        sa.Column("status", sa.Enum("invited", "active", "inactive", name="user_status"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["invited_by_id"], ["users.id"], name=op.f("fk_users_invited_by_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tid", "oid", name="uq_users_tid_oid"),
    )
    op.create_index("uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True)
    op.create_table(
        "batches",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("batch_no", sa.String(length=60), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("mfg_date", sa.Date(), nullable=True),
        sa.Column("mrp", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("supplier_name", sa.String(length=160), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], name=op.f("fk_batches_item_id_items")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
        sa.UniqueConstraint("item_id", "batch_no", name="uq_batches_item_batch"),
    )
    op.create_index(op.f("ix_batches_expiry_date"), "batches", ["expiry_date"], unique=False)
    op.create_index(op.f("ix_batches_item_id"), "batches", ["item_id"], unique=False)
    op.create_table(
        "pharmacy_orders",
        sa.Column("order_no", sa.String(length=40), nullable=False),
        sa.Column("channel", sa.Enum("counter_sale", "requisition", name="order_channel"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("allocated", "dispatched", "partially_returned", "returned", "cancelled", name="order_status"),
            nullable=False,
        ),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("walk_in_name", sa.String(length=160), nullable=True),
        sa.Column("walk_in_phone", sa.String(length=20), nullable=True),
        sa.Column("prescription_ref", sa.String(length=80), nullable=True),
        sa.Column("prescriber_name", sa.String(length=160), nullable=True),
        sa.Column("requested_by_id", sa.Uuid(), nullable=True),
        sa.Column("department", sa.String(length=120), nullable=True),
        sa.Column("surgery_ref", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gst_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("invoice_no", sa.String(length=40), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("dispatched_by_id", sa.Uuid(), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("fk_pharmacy_orders_created_by_id_users")),
        sa.ForeignKeyConstraint(
            ["dispatched_by_id"], ["users.id"], name=op.f("fk_pharmacy_orders_dispatched_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_pharmacy_orders_location_id_locations")
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], name=op.f("fk_pharmacy_orders_patient_id_patients")),
        sa.ForeignKeyConstraint(
            ["requested_by_id"], ["users.id"], name=op.f("fk_pharmacy_orders_requested_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pharmacy_orders")),
        sa.UniqueConstraint("invoice_no", name=op.f("uq_pharmacy_orders_invoice_no")),
        sa.UniqueConstraint("order_no", name=op.f("uq_pharmacy_orders_order_no")),
    )
    op.create_index(op.f("ix_pharmacy_orders_channel"), "pharmacy_orders", ["channel"], unique=False)
    op.create_index(op.f("ix_pharmacy_orders_requested_by_id"), "pharmacy_orders", ["requested_by_id"], unique=False)
    op.create_index(op.f("ix_pharmacy_orders_status"), "pharmacy_orders", ["status"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_code", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_code"],
            ["permissions.code"],
            name=op.f("fk_role_permissions_permission_code_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id_roles"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_code", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_by_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["assigned_by_id"], ["users.id"], name=op.f("fk_user_roles_assigned_by_id_users")),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_user_roles_location_id_locations"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint(
            "user_id", "role_id", "location_id", name="uq_user_roles_assignment", postgresql_nulls_not_distinct=True
        ),
    )
    op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.create_table(
        "pharmacy_order_lines",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], name=op.f("fk_pharmacy_order_lines_item_id_items")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["pharmacy_orders.id"],
            name=op.f("fk_pharmacy_order_lines_order_id_pharmacy_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pharmacy_order_lines")),
    )
    op.create_index(op.f("ix_pharmacy_order_lines_order_id"), "pharmacy_order_lines", ["order_id"], unique=False)
    op.create_table(
        "stock_balances",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("bin_code", sa.String(length=40), nullable=True),
        sa.Column("qty_on_hand", sa.Integer(), nullable=False),
        sa.Column("qty_reserved", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("qty_on_hand >= 0", name=op.f("ck_stock_balances_on_hand_non_negative")),
        sa.CheckConstraint(
            "qty_reserved >= 0 AND qty_reserved <= qty_on_hand", name=op.f("ck_stock_balances_reserved_within_on_hand")
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], name=op.f("fk_stock_balances_batch_id_batches")),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_stock_balances_location_id_locations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_balances")),
        sa.UniqueConstraint("batch_id", "location_id", name="uq_stock_balances_batch_location"),
    )
    op.create_index(op.f("ix_stock_balances_batch_id"), "stock_balances", ["batch_id"], unique=False)
    op.create_index(op.f("ix_stock_balances_location_id"), "stock_balances", ["location_id"], unique=False)
    op.create_table(
        "stock_ledger",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("qty_delta", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "receipt",
                "adjustment",
                "transfer_out",
                "transfer_in",
                "issue",
                "return_in",
                "writeoff",
                name="ledger_reason",
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("ref_type", sa.String(length=40), nullable=True),
        sa.Column("ref_id", sa.String(length=64), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_stock_ledger_actor_id_users")),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], name=op.f("fk_stock_ledger_batch_id_batches")),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], name=op.f("fk_stock_ledger_location_id_locations")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_ledger")),
    )
    op.create_index(op.f("ix_stock_ledger_batch_id"), "stock_ledger", ["batch_id"], unique=False)
    op.create_index(op.f("ix_stock_ledger_created_at"), "stock_ledger", ["created_at"], unique=False)
    op.create_index("ix_stock_ledger_ref", "stock_ledger", ["ref_type", "ref_id"], unique=False)
    op.create_table(
        "pharmacy_order_allocations",
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("qty_returned", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name=op.f("fk_pharmacy_order_allocations_batch_id_batches")
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["pharmacy_order_lines.id"],
            name=op.f("fk_pharmacy_order_allocations_line_id_pharmacy_order_lines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pharmacy_order_allocations")),
    )
    op.create_index(
        op.f("ix_pharmacy_order_allocations_line_id"), "pharmacy_order_allocations", ["line_id"], unique=False
    )
    # ### end Alembic commands ###

    # audit_log and stock_ledger are append-only: block UPDATE/DELETE at the database level.
    op.execute("""
        CREATE FUNCTION rxpulse_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
        END $$;
    """)
    for t in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
            f"FOR EACH ROW EXECUTE FUNCTION rxpulse_append_only()"
        )


def downgrade() -> None:
    for t in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t}")
    op.execute("DROP FUNCTION IF EXISTS rxpulse_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pharmacy_order_allocations_line_id"), table_name="pharmacy_order_allocations")
    op.drop_table("pharmacy_order_allocations")
    op.drop_index("ix_stock_ledger_ref", table_name="stock_ledger")
    op.drop_index(op.f("ix_stock_ledger_created_at"), table_name="stock_ledger")
    op.drop_index(op.f("ix_stock_ledger_batch_id"), table_name="stock_ledger")
    op.drop_table("stock_ledger")
    op.drop_index(op.f("ix_stock_balances_location_id"), table_name="stock_balances")
    op.drop_index(op.f("ix_stock_balances_batch_id"), table_name="stock_balances")
    op.drop_table("stock_balances")
    op.drop_index(op.f("ix_pharmacy_order_lines_order_id"), table_name="pharmacy_order_lines")
    op.drop_table("pharmacy_order_lines")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_pharmacy_orders_status"), table_name="pharmacy_orders")
    op.drop_index(op.f("ix_pharmacy_orders_requested_by_id"), table_name="pharmacy_orders")
    op.drop_index(op.f("ix_pharmacy_orders_channel"), table_name="pharmacy_orders")
    op.drop_table("pharmacy_orders")
    op.drop_index(op.f("ix_batches_item_id"), table_name="batches")
    op.drop_index(op.f("ix_batches_expiry_date"), table_name="batches")
    op.drop_table("batches")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_patients_name"), table_name="patients")
    op.drop_table("patients")
    op.drop_table("locations")
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_audit_log_ts"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
    for enum in (
        "order_status",
        "order_channel",
        "ledger_reason",
        "drug_schedule",
        "item_type",
        "user_status",
        "location_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum}")
    op.execute("DROP SEQUENCE IF EXISTS pharmacy_invoice_no_seq")
    op.execute("DROP SEQUENCE IF EXISTS pharmacy_order_no_seq")
